# Generated by Django 2.2.7 on 2020-07-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletterpromotion',
            old_name='post_related',
            new_name='promotion_related',
        ),
    ]
