# Generated by Django 2.2.7 on 2020-07-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20200711_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token',
            field=models.CharField(default=None, max_length=40, null=True, unique=True, verbose_name="Clé d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
