# Generated by Django 2.2.7 on 2019-12-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandline',
            options={'verbose_name': 'ligne de la commande', 'verbose_name_plural': 'lignes de la commande'},
        ),
        migrations.AlterField(
            model_name='promocart',
            name='promotion_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Promotion', verbose_name='solde liée'),
        ),
        migrations.AlterField(
            model_name='promocommand',
            name='promotion_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Promotion', verbose_name='solde liée'),
        ),
    ]
