# Generated by Django 2.2.7 on 2019-12-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20191216_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartline',
            options={'verbose_name': 'ligne de panier', 'verbose_name_plural': 'lignes du panier'},
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nom de la ville'),
        ),
    ]
