# Generated by Django 2.2.7 on 2019-12-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20191216_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profiles', verbose_name='image de profil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(upload_to='articles', verbose_name="changer l'image"),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, upload_to='articles', verbose_name="changer l'image"),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, upload_to='articles', verbose_name="changer l'image"),
        ),
        migrations.AlterField(
            model_name='article',
            name='image4',
            field=models.ImageField(blank=True, upload_to='articles', verbose_name="changer l'image"),
        ),
    ]
