# Generated by Django 2.2.7 on 2019-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20191217_0358'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='promotionline',
            constraint=models.CheckConstraint(check=models.Q(article_count__gte=1), name='gt_than_1'),
        ),
    ]
