# Generated by Django 2.2.7 on 2019-12-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20191218_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandline',
            name='furnisher_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Furnisher', verbose_name='Fournisseur le plus proche'),
        ),
    ]
