# Generated by Django 2.2.7 on 2020-02-17 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_commandline_furnisher_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id'], 'verbose_name': 'compte client', 'verbose_name_plural': 'comptes client'},
        ),
        migrations.AddField(
            model_name='article',
            name='commands',
            field=models.ManyToManyField(through='ecommerce.CommandLine', to='ecommerce.Command'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="prix de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name="Lien de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='stock restant'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='article_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="nombre d'articles"),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Lien de la catégorie'),
        ),
        migrations.AlterField(
            model_name='commandline',
            name='article_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="nombre d'articles"),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Lien de la promotion'),
        ),
        migrations.AlterField(
            model_name='promotionline',
            name='article_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="nombre d'articles"),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ordre de défilement'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='priority',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='priorité de la zone'),
        ),
    ]
