# Generated by Django 2.2.7 on 2020-02-17 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20200217_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Frais de livraison'),
        ),
    ]
