# Generated by Django 2.2.7 on 2020-02-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_commune_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='payment_modality',
            field=models.SmallIntegerField(choices=[(2, 'Mobile Money'), (1, 'Cash à la livraison')], verbose_name='méthode de payement'),
        ),
    ]
