# Generated by Django 2.2.7 on 2020-02-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20200217_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnisher',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.Zone', verbose_name='zone située'),
        ),
    ]
