# Generated by Django 2.2.7 on 2020-02-21 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20200217_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock restant'),
        ),
    ]
