# Generated by Django 2.2.7 on 2020-06-30 04:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20200221_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name'], 'verbose_name': 'produit'},
        ),
        migrations.AddField(
            model_name='article',
            name='new_until',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="nouveau jusqu'au"),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, verbose_name='description du produit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom du produit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='prix du produit'),
        ),
    ]
