# Generated by Django 2.2.7 on 2020-07-25 18:37

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20200711_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=filebrowser.fields.FileBrowseField(max_length=255, verbose_name="changer l'image"),
        ),
    ]
