# Generated by Django 2.2.7 on 2020-07-25 18:40

import boagroup_services.storage
from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20200725_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(storage=boagroup_services.storage.OverwriteStorage(), upload_to=utils.utils.PathAndRename('uploads/ecommerce/articles', 'image-1'), verbose_name="changer l'image"),
        ),
    ]
