# Generated by Django 2.2.7 on 2020-06-30 04:38

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import boagroup_services.storage
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0013_auto_20200630_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'editeur',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Lien de la catégorie')),
                ('image', models.ImageField(blank=True, storage=boagroup_services.storage.OverwriteStorage(), upload_to=blog.models.PathAndRename('blog-categories'), verbose_name='Image de la catégorie')),
            ],
            options={
                'verbose_name': 'catégorie',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.PositiveIntegerField(choices=[(1, 'Mis en Avant'), (2, 'Articles Populaires')], default=1, verbose_name='section')),
                ('show', models.BooleanField(default=True, verbose_name="Afficher l'article ?")),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='titre')),
                ('image', models.ImageField(upload_to='uploads', verbose_name="changer l'image")),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name="contenu de l'article")),
                ('date', models.DateField(auto_now=True, verbose_name='date de publication')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name="lien de l'article")),
                ('open', models.BooleanField(default=True, verbose_name='peut-on encore commenter sur cet article ?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author', verbose_name='éditeur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.Category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['-date'],
                'get_latest_by': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='mot')),
            ],
            options={
                'verbose_name': 'Mot-clé',
                'verbose_name_plural': 'Mots-clé',
            },
        ),
        migrations.CreateModel(
            name='TagLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Post')),
                ('tag_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tag', verbose_name='Mot-clé')),
            ],
            options={
                'verbose_name': 'Mot-clé',
                'verbose_name_plural': 'Mots-clé',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='blog.TagLine', to='blog.Tag'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='commenté le')),
                ('content', models.CharField(max_length=255, verbose_name='contenu')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Account', verbose_name='auteur')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='blog.Comment', verbose_name='Commentaire parent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post', verbose_name='article lié')),
            ],
            options={
                'verbose_name': 'commentaire',
                'ordering': ['-date'],
            },
        ),
    ]
