# Generated by Django 2.2.7 on 2020-07-11 19:22

import boagroup_services.storage
from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date'], 'verbose_name': 'commentaire'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, storage=boagroup_services.storage.OverwriteStorage(), upload_to=utils.utils.PathAndRename('uploads/blog/categories'), verbose_name='Image de la catégorie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=boagroup_services.storage.OverwriteStorage(), upload_to=utils.utils.PathAndRename('uploads/blog/articles'), verbose_name="changer l'image"),
        ),
        migrations.AlterField(
            model_name='post',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Ouvert ?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.PositiveIntegerField(choices=[(1, 'Articles Mis en Avant'), (2, 'Articles Populaires')], default=1, verbose_name='section'),
        ),
    ]
