# Generated by Django 2.2.7 on 2020-07-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200725_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.SmallIntegerField(choices=[(0, 'Aucune'), (1, 'Articles Mis en Avant'), (2, 'Articles Populaires')], default=0, verbose_name='section'),
        ),
    ]
