# Generated by Django 2.2.7 on 2020-07-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200725_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_created=True, verbose_name='vu le')),
                ('ip', models.GenericIPAddressField(verbose_name='addresse IP')),
                ('post_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='article lié')),
            ],
            options={
                'verbose_name': 'Vue',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
