# Generated by Django 2.2.7 on 2020-07-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='vu le'),
        ),
    ]
