# Generated by Django 2.2.7 on 2020-08-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200726_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='open',
        ),
    ]
